// ─── Complete Word List ───
// Each word has a unique id, a level (game type), and its word/hint/category.
//
// Levels:
//   "children_easy"    — 3-letter words for young beginners
//   "children_medium"  — 4-5 letter words with phonics
//   "children_hard"    — Longer words with tricky spellings
//   "adult_standard"   — Interesting vocabulary, 8 lives
//   "adult_challenge"  — Obscure & difficult, 6 lives

const WORDS = [
  // ══════════════════════════════════════════════════════════════════
  // ── Children Easy (3-letter words) ──
  // ══════════════════════════════════════════════════════════════════
  // Animals
  { id: 1,   level: "children_easy", word: "CAT",  hint: "A furry pet that purrs",              category: "Animals" },
  { id: 2,   level: "children_easy", word: "DOG",  hint: "A loyal pet that barks",              category: "Animals" },
  { id: 3,   level: "children_easy", word: "PIG",  hint: "Pink farm animal",                    category: "Animals" },
  { id: 4,   level: "children_easy", word: "HEN",  hint: "A chicken that lays eggs",            category: "Animals" },
  { id: 5,   level: "children_easy", word: "COW",  hint: "Farm animal that gives milk",         category: "Animals" },
  { id: 6,   level: "children_easy", word: "ANT",  hint: "Tiny insect that works in a team",    category: "Animals" },
  { id: 7,   level: "children_easy", word: "BEE",  hint: "Buzzing insect that makes honey",     category: "Animals" },
  { id: 8,   level: "children_easy", word: "BAT",  hint: "Flying animal that comes out at night", category: "Animals" },
  { id: 9,   level: "children_easy", word: "RAM",  hint: "A male sheep with curly horns",       category: "Animals" },
  { id: 10,  level: "children_easy", word: "YAK",  hint: "Big hairy animal from the mountains", category: "Animals" },
  { id: 11,  level: "children_easy", word: "EWE",  hint: "A female sheep",                      category: "Animals" },
  { id: 12,  level: "children_easy", word: "EMU",  hint: "A big bird that cannot fly",          category: "Animals" },
  { id: 13,  level: "children_easy", word: "APE",  hint: "An animal like a big monkey",         category: "Animals" },
  { id: 14,  level: "children_easy", word: "CUB",  hint: "A baby bear",                         category: "Animals" },
  { id: 15,  level: "children_easy", word: "FOX",  hint: "A clever orange animal",              category: "Animals" },
  { id: 16,  level: "children_easy", word: "OWL",  hint: "A bird that hoots at night",          category: "Animals" },
  // Nature
  { id: 17,  level: "children_easy", word: "SUN",  hint: "Bright and warm in the sky",          category: "Nature" },
  { id: 18,  level: "children_easy", word: "SKY",  hint: "Look up and you will see it",         category: "Nature" },
  { id: 19,  level: "children_easy", word: "SEA",  hint: "Big body of salty water",             category: "Nature" },
  { id: 20,  level: "children_easy", word: "MUD",  hint: "Wet dirty earth",                     category: "Nature" },
  { id: 21,  level: "children_easy", word: "ICE",  hint: "Frozen water",                        category: "Nature" },
  { id: 22,  level: "children_easy", word: "DEW",  hint: "Tiny water drops on grass in the morning", category: "Nature" },
  { id: 23,  level: "children_easy", word: "LOG",  hint: "A big piece of a tree trunk",         category: "Nature" },
  { id: 24,  level: "children_easy", word: "IVY",  hint: "A climbing green plant",              category: "Nature" },
  // Home
  { id: 25,  level: "children_easy", word: "BED",  hint: "Where you sleep at night",            category: "Home" },
  { id: 26,  level: "children_easy", word: "CUP",  hint: "You drink from it",                   category: "Home" },
  { id: 27,  level: "children_easy", word: "MOP",  hint: "Cleans the floor",                    category: "Home" },
  { id: 28,  level: "children_easy", word: "MUG",  hint: "A big cup for hot drinks",            category: "Home" },
  { id: 29,  level: "children_easy", word: "RUG",  hint: "A small soft carpet",                 category: "Home" },
  { id: 30,  level: "children_easy", word: "JAR",  hint: "A glass container with a lid",        category: "Home" },
  { id: 31,  level: "children_easy", word: "TAP",  hint: "Turn it to get water",                category: "Home" },
  { id: 32,  level: "children_easy", word: "BIN",  hint: "Where you put rubbish",               category: "Home" },
  { id: 33,  level: "children_easy", word: "MAT",  hint: "You wipe your feet on it",            category: "Home" },
  { id: 34,  level: "children_easy", word: "PAN",  hint: "You cook food in it",                 category: "Home" },
  { id: 35,  level: "children_easy", word: "POT",  hint: "You boil water in it",                category: "Home" },
  { id: 36,  level: "children_easy", word: "LID",  hint: "The top of a box or jar",             category: "Home" },
  // Food
  { id: 37,  level: "children_easy", word: "JAM",  hint: "Sweet spread for toast",              category: "Food" },
  { id: 38,  level: "children_easy", word: "PIE",  hint: "Baked food with a pastry crust",      category: "Food" },
  { id: 39,  level: "children_easy", word: "PEA",  hint: "Small round green vegetable",         category: "Food" },
  { id: 40,  level: "children_easy", word: "NUT",  hint: "A hard-shelled snack",                category: "Food" },
  { id: 41,  level: "children_easy", word: "FIG",  hint: "A soft sweet fruit",                  category: "Food" },
  { id: 42,  level: "children_easy", word: "HAM",  hint: "Meat from a pig",                     category: "Food" },
  { id: 43,  level: "children_easy", word: "YAM",  hint: "A vegetable like a sweet potato",     category: "Food" },
  { id: 44,  level: "children_easy", word: "OAT",  hint: "Grain used to make porridge",         category: "Food" },
  // Transport
  { id: 45,  level: "children_easy", word: "BUS",  hint: "Big vehicle that carries people",     category: "Transport" },
  { id: 46,  level: "children_easy", word: "CAR",  hint: "You ride in it on the road",          category: "Transport" },
  { id: 47,  level: "children_easy", word: "VAN",  hint: "A vehicle for carrying things",       category: "Transport" },
  { id: 48,  level: "children_easy", word: "CAB",  hint: "A taxi",                              category: "Transport" },
  // Clothes
  { id: 49,  level: "children_easy", word: "HAT",  hint: "You wear it on your head",            category: "Clothes" },
  { id: 50,  level: "children_easy", word: "WIG",  hint: "Fake hair you can put on",            category: "Clothes" },
  { id: 51,  level: "children_easy", word: "BIB",  hint: "Keeps a baby clean at mealtimes",     category: "Clothes" },
  { id: 52,  level: "children_easy", word: "BOW",  hint: "A pretty tied ribbon",                category: "Clothes" },
  // School & Things
  { id: 53,  level: "children_easy", word: "PEN",  hint: "You write with it",                   category: "School" },
  { id: 54,  level: "children_easy", word: "NET",  hint: "Used to catch fish or butterflies",   category: "Things" },
  { id: 55,  level: "children_easy", word: "BOX",  hint: "You put things inside it",            category: "Things" },
  { id: 56,  level: "children_easy", word: "BAG",  hint: "You carry your things in it",         category: "Things" },
  { id: 57,  level: "children_easy", word: "TOY",  hint: "Something you play with",             category: "Things" },
  { id: 58,  level: "children_easy", word: "MAP",  hint: "Shows you where places are",          category: "Things" },
  { id: 59,  level: "children_easy", word: "KEY",  hint: "Opens a lock",                        category: "Things" },
  { id: 60,  level: "children_easy", word: "PIN",  hint: "A tiny sharp metal stick",            category: "Things" },
  // Colours
  { id: 61,  level: "children_easy", word: "RED",  hint: "The colour of a fire engine",         category: "Colours" },
  { id: 62,  level: "children_easy", word: "TAN",  hint: "A light brown colour",                category: "Colours" },
  // Actions
  { id: 63,  level: "children_easy", word: "RUN",  hint: "Move your legs fast",                 category: "Actions" },
  { id: 64,  level: "children_easy", word: "HOP",  hint: "Jump on one foot",                    category: "Actions" },
  { id: 65,  level: "children_easy", word: "SIT",  hint: "Rest on a chair",                     category: "Actions" },
  { id: 66,  level: "children_easy", word: "HUG",  hint: "Put your arms around someone",        category: "Actions" },
  { id: 67,  level: "children_easy", word: "DIG",  hint: "Make a hole in the ground",           category: "Actions" },
  { id: 68,  level: "children_easy", word: "CRY",  hint: "Tears come from your eyes",           category: "Actions" },
  { id: 69,  level: "children_easy", word: "FLY",  hint: "Move through the air",                category: "Actions" },
  { id: 70,  level: "children_easy", word: "MIX",  hint: "Stir things together",                category: "Actions" },
  { id: 71,  level: "children_easy", word: "CUT",  hint: "Use scissors to do this",             category: "Actions" },
  { id: 72,  level: "children_easy", word: "HIT",  hint: "Strike something",                    category: "Actions" },
  { id: 73,  level: "children_easy", word: "WIN",  hint: "Come first in a race",                category: "Actions" },
  { id: 74,  level: "children_easy", word: "TUG",  hint: "Pull something hard",                 category: "Actions" },
  // Describing
  { id: 75,  level: "children_easy", word: "BIG",  hint: "Not small",                           category: "Describing" },
  { id: 76,  level: "children_easy", word: "HOT",  hint: "Very warm",                           category: "Describing" },
  { id: 77,  level: "children_easy", word: "WET",  hint: "Covered in water",                    category: "Describing" },
  { id: 78,  level: "children_easy", word: "OLD",  hint: "Not new or young",                    category: "Describing" },
  { id: 79,  level: "children_easy", word: "SAD",  hint: "Not happy",                           category: "Describing" },
  { id: 80,  level: "children_easy", word: "NEW",  hint: "Not old, just made",                  category: "Describing" },
  // Feelings
  { id: 81,  level: "children_easy", word: "FUN",  hint: "When you're having a great time",     category: "Feelings" },
  { id: 82,  level: "children_easy", word: "JOY",  hint: "A happy feeling",                     category: "Feelings" },
  // Body
  { id: 83,  level: "children_easy", word: "ARM",  hint: "Between your shoulder and hand",      category: "Body" },
  { id: 84,  level: "children_easy", word: "LEG",  hint: "You stand on two of these",           category: "Body" },
  { id: 85,  level: "children_easy", word: "EAR",  hint: "You hear with it",                    category: "Body" },
  { id: 86,  level: "children_easy", word: "EYE",  hint: "You see with it",                     category: "Body" },
  { id: 87,  level: "children_easy", word: "TOE",  hint: "You have five on each foot",          category: "Body" },
  { id: 88,  level: "children_easy", word: "RIB",  hint: "A bone in your chest",                category: "Body" },
  { id: 89,  level: "children_easy", word: "JAW",  hint: "The bone in your chin",               category: "Body" },
  { id: 90,  level: "children_easy", word: "GUM",  hint: "The pink part around your teeth",     category: "Body" },
  // People
  { id: 91,  level: "children_easy", word: "MUM",  hint: "Your mother",                         category: "People" },
  { id: 92,  level: "children_easy", word: "DAD",  hint: "Your father",                         category: "People" },
  { id: 93,  level: "children_easy", word: "BOY",  hint: "A young male person",                 category: "People" },
  { id: 94,  level: "children_easy", word: "LAD",  hint: "Another word for a boy",              category: "People" },
  // Places
  { id: 95,  level: "children_easy", word: "ZOO",  hint: "Where you go to see animals",         category: "Places" },
  { id: 96,  level: "children_easy", word: "DEN",  hint: "An animal's home",                    category: "Places" },
  // Weather
  { id: 97,  level: "children_easy", word: "FOG",  hint: "Thick misty air",                     category: "Weather" },

  // ══════════════════════════════════════════════════════════════════
  // ── Children Medium (4-6 letter words) ──
  // ══════════════════════════════════════════════════════════════════
  // Animals
  { id: 98,  level: "children_medium", word: "FISH",    hint: "Swims in water",                    category: "Animals" },
  { id: 99,  level: "children_medium", word: "BIRD",    hint: "Has feathers and can fly",           category: "Animals" },
  { id: 100, level: "children_medium", word: "FROG",    hint: "Green and hops around ponds",        category: "Animals" },
  { id: 101, level: "children_medium", word: "SHEEP",   hint: "Woolly farm animal",                 category: "Animals" },
  { id: 102, level: "children_medium", word: "SHARK",   hint: "Big fish with sharp teeth",          category: "Animals" },
  { id: 103, level: "children_medium", word: "DUCK",    hint: "A bird that quacks",                 category: "Animals" },
  { id: 104, level: "children_medium", word: "GOAT",    hint: "Farm animal with a little beard",    category: "Animals" },
  { id: 105, level: "children_medium", word: "BEAR",    hint: "Big furry animal in the woods",      category: "Animals" },
  { id: 106, level: "children_medium", word: "DEER",    hint: "Gentle animal with antlers",         category: "Animals" },
  { id: 107, level: "children_medium", word: "WOLF",    hint: "Wild cousin of the dog",             category: "Animals" },
  { id: 108, level: "children_medium", word: "CRAB",    hint: "Has claws and walks sideways",       category: "Animals" },
  { id: 109, level: "children_medium", word: "SWAN",    hint: "An elegant white bird on a lake",    category: "Animals" },
  { id: 110, level: "children_medium", word: "TOAD",    hint: "Like a frog but bumpier",            category: "Animals" },
  { id: 111, level: "children_medium", word: "MOLE",    hint: "Digs tunnels underground",           category: "Animals" },
  { id: 112, level: "children_medium", word: "WORM",    hint: "Long and wiggly in the soil",        category: "Animals" },
  { id: 113, level: "children_medium", word: "SEAL",    hint: "Claps its flippers and barks",       category: "Animals" },
  { id: 114, level: "children_medium", word: "SNAIL",   hint: "Carries its house on its back",      category: "Animals" },
  { id: 115, level: "children_medium", word: "MOUSE",   hint: "Tiny animal that squeaks",           category: "Animals" },
  { id: 116, level: "children_medium", word: "WHALE",   hint: "The biggest animal in the sea",      category: "Animals" },
  { id: 117, level: "children_medium", word: "HORSE",   hint: "You can ride it and it neighs",      category: "Animals" },
  { id: 118, level: "children_medium", word: "ZEBRA",   hint: "Black and white stripy animal",      category: "Animals" },
  { id: 119, level: "children_medium", word: "TIGER",   hint: "Big stripy wild cat",                category: "Animals" },
  { id: 120, level: "children_medium", word: "PANDA",   hint: "Black and white bear from China",    category: "Animals" },
  { id: 121, level: "children_medium", word: "CAMEL",   hint: "Has a hump and lives in the desert", category: "Animals" },
  { id: 122, level: "children_medium", word: "ROBIN",   hint: "A bird with a red breast",           category: "Animals" },
  { id: 123, level: "children_medium", word: "EAGLE",   hint: "A big bird of prey",                 category: "Animals" },
  { id: 124, level: "children_medium", word: "KOALA",   hint: "Australian animal that eats leaves", category: "Animals" },
  { id: 125, level: "children_medium", word: "LLAMA",   hint: "Fluffy animal from South America",   category: "Animals" },
  { id: 126, level: "children_medium", word: "OTTER",   hint: "Playful animal that swims in rivers", category: "Animals" },
  { id: 127, level: "children_medium", word: "PUPPY",   hint: "A baby dog",                         category: "Animals" },
  // Nature
  { id: 128, level: "children_medium", word: "TREE",    hint: "Has leaves and branches",            category: "Nature" },
  { id: 129, level: "children_medium", word: "MOON",    hint: "Shines at night",                    category: "Nature" },
  { id: 130, level: "children_medium", word: "STAR",    hint: "Twinkles in the night sky",          category: "Nature" },
  { id: 131, level: "children_medium", word: "RAIN",    hint: "Water falling from clouds",          category: "Nature" },
  { id: 132, level: "children_medium", word: "LAKE",    hint: "A body of water surrounded by land", category: "Nature" },
  { id: 133, level: "children_medium", word: "HILL",    hint: "A small mountain",                   category: "Nature" },
  { id: 134, level: "children_medium", word: "POND",    hint: "A small pool of water",              category: "Nature" },
  { id: 135, level: "children_medium", word: "SEED",    hint: "Plant it and watch it grow",         category: "Nature" },
  { id: 136, level: "children_medium", word: "LEAF",    hint: "Green and grows on a tree",          category: "Nature" },
  { id: 137, level: "children_medium", word: "ROSE",    hint: "A beautiful flower with thorns",     category: "Nature" },
  { id: 138, level: "children_medium", word: "BUSH",    hint: "A short thick plant",                category: "Nature" },
  { id: 139, level: "children_medium", word: "WAVE",    hint: "Water rising up in the sea",         category: "Nature" },
  { id: 140, level: "children_medium", word: "SNOW",    hint: "Cold white flakes from the sky",     category: "Nature" },
  { id: 141, level: "children_medium", word: "WIND",    hint: "Moving air you can feel",            category: "Nature" },
  { id: 142, level: "children_medium", word: "CAVE",    hint: "A hole in the side of a hill",       category: "Nature" },
  { id: 143, level: "children_medium", word: "RIVER",   hint: "Water that flows to the sea",        category: "Nature" },
  { id: 144, level: "children_medium", word: "STONE",   hint: "A small piece of rock",              category: "Nature" },
  { id: 145, level: "children_medium", word: "FIELD",   hint: "A big open grassy area",             category: "Nature" },
  { id: 146, level: "children_medium", word: "CORAL",   hint: "Colourful thing under the sea",      category: "Nature" },
  // Transport
  { id: 147, level: "children_medium", word: "SHIP",    hint: "Sails on the ocean",                 category: "Transport" },
  { id: 148, level: "children_medium", word: "TRAIN",   hint: "Rides on tracks",                    category: "Transport" },
  { id: 149, level: "children_medium", word: "PLANE",   hint: "Flies through the sky",              category: "Transport" },
  { id: 150, level: "children_medium", word: "BOAT",    hint: "Floats on water",                    category: "Transport" },
  { id: 151, level: "children_medium", word: "BIKE",    hint: "Two wheels and pedals",              category: "Transport" },
  { id: 152, level: "children_medium", word: "CANOE",   hint: "A small boat you paddle",            category: "Transport" },
  { id: 153, level: "children_medium", word: "LORRY",   hint: "A big truck",                        category: "Transport" },
  // Food
  { id: 154, level: "children_medium", word: "CAKE",    hint: "Sweet treat for birthdays",          category: "Food" },
  { id: 155, level: "children_medium", word: "RICE",    hint: "Small white grains you cook",        category: "Food" },
  { id: 156, level: "children_medium", word: "MILK",    hint: "White drink from a cow",             category: "Food" },
  { id: 157, level: "children_medium", word: "SOUP",    hint: "Hot liquid food in a bowl",          category: "Food" },
  { id: 158, level: "children_medium", word: "PLUM",    hint: "A small purple fruit",               category: "Food" },
  { id: 159, level: "children_medium", word: "CORN",    hint: "Yellow vegetable on a cob",          category: "Food" },
  { id: 160, level: "children_medium", word: "BREAD",   hint: "You make sandwiches with it",        category: "Food" },
  { id: 161, level: "children_medium", word: "GRAPE",   hint: "Small round fruit in bunches",       category: "Food" },
  { id: 162, level: "children_medium", word: "PEACH",   hint: "A soft fuzzy fruit",                 category: "Food" },
  { id: 163, level: "children_medium", word: "CANDY",   hint: "Sweet sugary treat",                 category: "Food" },
  { id: 164, level: "children_medium", word: "LEMON",   hint: "A sour yellow fruit",                category: "Food" },
  { id: 165, level: "children_medium", word: "MANGO",   hint: "A sweet tropical fruit",             category: "Food" },
  { id: 166, level: "children_medium", word: "PASTA",   hint: "Italian food like spaghetti",        category: "Food" },
  { id: 167, level: "children_medium", word: "PIZZA",   hint: "Round food with cheese on top",      category: "Food" },
  { id: 168, level: "children_medium", word: "TOAST",   hint: "Crunchy cooked bread",               category: "Food" },
  // Home
  { id: 169, level: "children_medium", word: "CHAIR",   hint: "You sit on it",                      category: "Home" },
  { id: 170, level: "children_medium", word: "LIGHT",   hint: "Helps you see in the dark",          category: "Home" },
  { id: 171, level: "children_medium", word: "TABLE",   hint: "You eat dinner on it",               category: "Home" },
  { id: 172, level: "children_medium", word: "CLOCK",   hint: "Tells you the time",                 category: "Home" },
  { id: 173, level: "children_medium", word: "BRUSH",   hint: "You use it on your hair or teeth",   category: "Home" },
  { id: 174, level: "children_medium", word: "TOWEL",   hint: "You dry yourself with it",           category: "Home" },
  { id: 175, level: "children_medium", word: "STAIR",   hint: "Steps going up or down",             category: "Home" },
  { id: 176, level: "children_medium", word: "SHELF",   hint: "You put books on it",                category: "Home" },
  { id: 177, level: "children_medium", word: "PLATE",   hint: "You put your food on it",            category: "Home" },
  { id: 178, level: "children_medium", word: "SPOON",   hint: "You eat soup with it",               category: "Home" },
  { id: 179, level: "children_medium", word: "STOOL",   hint: "A seat with no back",                category: "Home" },
  { id: 180, level: "children_medium", word: "BROOM",   hint: "You sweep the floor with it",        category: "Home" },
  { id: 181, level: "children_medium", word: "FENCE",   hint: "A barrier around a garden",          category: "Home" },
  // School
  { id: 182, level: "children_medium", word: "BOOK",    hint: "You read stories in it",             category: "School" },
  { id: 183, level: "children_medium", word: "RULER",   hint: "You measure with it",                category: "School" },
  { id: 184, level: "children_medium", word: "CHALK",   hint: "You write on a board with it",       category: "School" },
  { id: 185, level: "children_medium", word: "PAPER",   hint: "You write and draw on it",           category: "School" },
  { id: 186, level: "children_medium", word: "PAINT",   hint: "You use it to make pictures",        category: "School" },
  { id: 187, level: "children_medium", word: "GLOBE",   hint: "A round model of the Earth",         category: "School" },
  // Weather
  { id: 188, level: "children_medium", word: "CLOUD",   hint: "White and fluffy in the sky",        category: "Weather" },
  { id: 189, level: "children_medium", word: "STORM",   hint: "Loud thunder and lightning",         category: "Weather" },
  { id: 190, level: "children_medium", word: "FROST",   hint: "Icy crystals on the ground",         category: "Weather" },
  { id: 191, level: "children_medium", word: "SLEET",   hint: "A mix of rain and snow",             category: "Weather" },
  // People
  { id: 192, level: "children_medium", word: "QUEEN",   hint: "She wears a crown",                  category: "People" },
  { id: 193, level: "children_medium", word: "KNIGHT",  hint: "Wore armour and rode horses",        category: "People" },
  { id: 194, level: "children_medium", word: "NURSE",   hint: "Helps look after sick people",       category: "People" },
  { id: 195, level: "children_medium", word: "PILOT",   hint: "Flies an aeroplane",                 category: "People" },
  { id: 196, level: "children_medium", word: "CLOWN",   hint: "Makes people laugh at the circus",   category: "People" },
  { id: 197, level: "children_medium", word: "CHIEF",   hint: "The leader of a group",              category: "People" },
  { id: 198, level: "children_medium", word: "FAIRY",   hint: "A tiny magical person with wings",   category: "People" },
  { id: 199, level: "children_medium", word: "GIANT",   hint: "A very very tall person in stories", category: "People" },
  { id: 200, level: "children_medium", word: "PIRATE",  hint: "Sails the seas looking for treasure", category: "People" },
  // Places
  { id: 201, level: "children_medium", word: "BEACH",   hint: "Sandy place by the sea",             category: "Places" },
  { id: 202, level: "children_medium", word: "FARM",    hint: "Where animals and crops are kept",   category: "Places" },
  { id: 203, level: "children_medium", word: "PARK",    hint: "A green space to play in",           category: "Places" },
  { id: 204, level: "children_medium", word: "TOWER",   hint: "A tall narrow building",             category: "Places" },
  { id: 205, level: "children_medium", word: "CASTLE",  hint: "A big stone building for kings",     category: "Places" },
  { id: 206, level: "children_medium", word: "ISLAND",  hint: "Land surrounded by water",           category: "Places" },
  { id: 207, level: "children_medium", word: "JUNGLE",  hint: "A thick tropical forest",            category: "Places" },
  // Things
  { id: 208, level: "children_medium", word: "THUMB",   hint: "The short finger on your hand",      category: "Body" },
  { id: 209, level: "children_medium", word: "CROWN",   hint: "A king or queen wears it",           category: "Things" },
  { id: 210, level: "children_medium", word: "SWORD",   hint: "A long sharp weapon",                category: "Things" },
  { id: 211, level: "children_medium", word: "WHEEL",   hint: "Round and rolls along",              category: "Things" },
  { id: 212, level: "children_medium", word: "DRUM",    hint: "You hit it to make music",           category: "Things" },
  { id: 213, level: "children_medium", word: "FLUTE",   hint: "A musical instrument you blow",      category: "Things" },
  { id: 214, level: "children_medium", word: "BRICK",   hint: "Used to build walls and houses",     category: "Things" },
  { id: 215, level: "children_medium", word: "TORCH",   hint: "A light you can carry",              category: "Things" },
  { id: 216, level: "children_medium", word: "MEDAL",   hint: "A prize you wear round your neck",   category: "Things" },
  { id: 217, level: "children_medium", word: "CHAIN",   hint: "Metal links joined together",        category: "Things" },
  { id: 218, level: "children_medium", word: "KITE",    hint: "Flies on a string in the wind",      category: "Things" },
  { id: 219, level: "children_medium", word: "BADGE",   hint: "A small pin you wear",               category: "Things" },
  { id: 220, level: "children_medium", word: "PEARL",   hint: "A shiny gem from an oyster",         category: "Things" },
  // Actions
  { id: 221, level: "children_medium", word: "CLIMB",   hint: "Go up using hands and feet",         category: "Actions" },
  { id: 222, level: "children_medium", word: "DANCE",   hint: "Move to music",                      category: "Actions" },
  { id: 223, level: "children_medium", word: "DREAM",   hint: "Stories in your head while sleeping", category: "Actions" },
  { id: 224, level: "children_medium", word: "SMILE",   hint: "A happy face",                       category: "Actions" },
  { id: 225, level: "children_medium", word: "SHOUT",   hint: "Say something very loudly",          category: "Actions" },
  { id: 226, level: "children_medium", word: "CATCH",   hint: "Grab something in the air",          category: "Actions" },
  { id: 227, level: "children_medium", word: "THROW",   hint: "Send something through the air",     category: "Actions" },
  { id: 228, level: "children_medium", word: "FLOAT",   hint: "Stay on top of water",               category: "Actions" },
  { id: 229, level: "children_medium", word: "CRAWL",   hint: "Move on your hands and knees",       category: "Actions" },
  { id: 230, level: "children_medium", word: "SWING",   hint: "Move back and forth in the air",     category: "Actions" },
  { id: 231, level: "children_medium", word: "WRITE",   hint: "Put words on paper",                 category: "Actions" },
  { id: 232, level: "children_medium", word: "SLEEP",   hint: "Close your eyes and rest",           category: "Actions" },

  // ══════════════════════════════════════════════════════════════════
  // ── Children Hard (6+ letter words) ──
  // ══════════════════════════════════════════════════════════════════
  // Animals
  { id: 233, level: "children_hard", word: "BUTTERFLY",  hint: "Colourful insect with big wings",     category: "Animals" },
  { id: 234, level: "children_hard", word: "ELEPHANT",   hint: "Huge animal with a trunk",            category: "Animals" },
  { id: 235, level: "children_hard", word: "PENGUIN",    hint: "Black and white bird that waddles",   category: "Animals" },
  { id: 236, level: "children_hard", word: "DINOSAUR",   hint: "Lived millions of years ago",         category: "Animals" },
  { id: 237, level: "children_hard", word: "DOLPHIN",    hint: "Clever sea creature",                 category: "Animals" },
  { id: 238, level: "children_hard", word: "GIRAFFE",    hint: "Tallest animal on Earth",             category: "Animals" },
  { id: 239, level: "children_hard", word: "CHEETAH",    hint: "The fastest land animal",             category: "Animals" },
  { id: 240, level: "children_hard", word: "GORILLA",    hint: "A very large strong ape",             category: "Animals" },
  { id: 241, level: "children_hard", word: "HAMSTER",    hint: "Small fluffy pet with pouchy cheeks", category: "Animals" },
  { id: 242, level: "children_hard", word: "LEOPARD",    hint: "Big cat with spots",                  category: "Animals" },
  { id: 243, level: "children_hard", word: "LOBSTER",    hint: "Red sea creature with big claws",     category: "Animals" },
  { id: 244, level: "children_hard", word: "OCTOPUS",    hint: "Sea creature with eight arms",        category: "Animals" },
  { id: 245, level: "children_hard", word: "PARROT",     hint: "Colourful bird that can talk",        category: "Animals" },
  { id: 246, level: "children_hard", word: "RABBIT",     hint: "Fluffy animal with long ears",        category: "Animals" },
  { id: 247, level: "children_hard", word: "TORTOISE",   hint: "Slow animal with a hard shell",       category: "Animals" },
  { id: 248, level: "children_hard", word: "SQUIRREL",   hint: "Bushy-tailed animal that collects nuts", category: "Animals" },
  { id: 249, level: "children_hard", word: "FLAMINGO",   hint: "Tall pink bird that stands on one leg", category: "Animals" },
  { id: 250, level: "children_hard", word: "HEDGEHOG",   hint: "Small prickly animal",                category: "Animals" },
  { id: 251, level: "children_hard", word: "JELLYFISH",  hint: "See-through sea creature that stings", category: "Animals" },
  { id: 252, level: "children_hard", word: "KANGAROO",   hint: "Australian animal that hops with a pouch", category: "Animals" },
  { id: 253, level: "children_hard", word: "CROCODILE",  hint: "Big scaly reptile with strong jaws",  category: "Animals" },
  { id: 254, level: "children_hard", word: "CHAMELEON",  hint: "A lizard that changes colour",        category: "Animals" },
  { id: 255, level: "children_hard", word: "DRAGONFLY",  hint: "Insect with shiny wings near water",  category: "Animals" },
  { id: 256, level: "children_hard", word: "PORCUPINE",  hint: "Animal covered in sharp quills",      category: "Animals" },
  { id: 257, level: "children_hard", word: "CATERPILLAR", hint: "Turns into a butterfly",             category: "Animals" },
  // Nature
  { id: 258, level: "children_hard", word: "RAINBOW",    hint: "Colourful arc after rain",            category: "Nature" },
  { id: 259, level: "children_hard", word: "VOLCANO",    hint: "Mountain that erupts with lava",      category: "Nature" },
  { id: 260, level: "children_hard", word: "TORNADO",    hint: "A spinning funnel of wind",           category: "Nature" },
  { id: 261, level: "children_hard", word: "ICEBERG",    hint: "Huge chunk of floating ice",          category: "Nature" },
  { id: 262, level: "children_hard", word: "THUNDER",    hint: "The loud boom after lightning",       category: "Nature" },
  { id: 263, level: "children_hard", word: "BLOSSOM",    hint: "Flowers on a tree in spring",         category: "Nature" },
  { id: 264, level: "children_hard", word: "GLACIER",    hint: "A huge slow-moving river of ice",     category: "Nature" },
  { id: 265, level: "children_hard", word: "MOUNTAIN",   hint: "A very tall piece of land",           category: "Nature" },
  { id: 266, level: "children_hard", word: "WATERFALL",  hint: "Water that falls over a cliff",       category: "Nature" },
  { id: 267, level: "children_hard", word: "SUNSHINE",   hint: "Bright light from the sun",           category: "Nature" },
  { id: 268, level: "children_hard", word: "MUSHROOM",   hint: "Grows on the ground, looks like an umbrella", category: "Nature" },
  { id: 269, level: "children_hard", word: "SUNFLOWER",  hint: "A tall yellow flower",                category: "Nature" },
  // Food
  { id: 270, level: "children_hard", word: "CHOCOLATE",  hint: "Sweet brown treat",                   category: "Food" },
  { id: 271, level: "children_hard", word: "SANDWICH",   hint: "Filling between two slices of bread", category: "Food" },
  { id: 272, level: "children_hard", word: "BROCCOLI",   hint: "Green vegetable like a tiny tree",    category: "Food" },
  { id: 273, level: "children_hard", word: "SPAGHETTI",  hint: "Long thin pasta",                     category: "Food" },
  { id: 274, level: "children_hard", word: "PANCAKE",    hint: "Flat round food you flip",            category: "Food" },
  { id: 275, level: "children_hard", word: "BISCUIT",    hint: "A small crispy baked snack",          category: "Food" },
  { id: 276, level: "children_hard", word: "DOUGHNUT",   hint: "A ring-shaped sweet treat",           category: "Food" },
  { id: 277, level: "children_hard", word: "PINEAPPLE",  hint: "Spiky tropical fruit",                category: "Food" },
  { id: 278, level: "children_hard", word: "STRAWBERRY", hint: "Small red fruit with seeds outside",  category: "Food" },
  { id: 279, level: "children_hard", word: "BLUEBERRY",  hint: "Tiny round blue fruit",               category: "Food" },
  { id: 280, level: "children_hard", word: "POPCORN",    hint: "Snack that pops when heated",         category: "Food" },
  // Things
  { id: 281, level: "children_hard", word: "TREASURE",   hint: "Hidden gold and jewels",              category: "Things" },
  { id: 282, level: "children_hard", word: "TELEPHONE",  hint: "You use it to call people",           category: "Things" },
  { id: 283, level: "children_hard", word: "UMBRELLA",   hint: "Keeps you dry in the rain",           category: "Things" },
  { id: 284, level: "children_hard", word: "TELESCOPE",  hint: "You look through it to see far away", category: "Things" },
  { id: 285, level: "children_hard", word: "BACKPACK",   hint: "A bag you wear on your back",         category: "Things" },
  { id: 286, level: "children_hard", word: "NECKLACE",   hint: "Jewellery you wear around your neck", category: "Things" },
  { id: 287, level: "children_hard", word: "SCISSORS",   hint: "You cut paper with them",             category: "Things" },
  { id: 288, level: "children_hard", word: "CALENDAR",   hint: "Shows all the days and months",       category: "Things" },
  { id: 289, level: "children_hard", word: "COMPASS",    hint: "Points north to help you find your way", category: "Things" },
  { id: 290, level: "children_hard", word: "LANTERN",    hint: "A lamp you can carry",                category: "Things" },
  { id: 291, level: "children_hard", word: "TRAMPOLINE", hint: "You bounce on it",                    category: "Things" },
  { id: 292, level: "children_hard", word: "PARACHUTE",  hint: "Slows you down when falling from the sky", category: "Things" },
  { id: 293, level: "children_hard", word: "BINOCULARS", hint: "Makes far away things look close",    category: "Things" },
  // People
  { id: 294, level: "children_hard", word: "ASTRONAUT",  hint: "Travels to space",                    category: "People" },
  { id: 295, level: "children_hard", word: "PRINCESS",   hint: "The daughter of a king and queen",    category: "People" },
  { id: 296, level: "children_hard", word: "DETECTIVE",  hint: "Solves mysteries and crimes",         category: "People" },
  { id: 297, level: "children_hard", word: "SCIENTIST",  hint: "Studies how the world works",         category: "People" },
  { id: 298, level: "children_hard", word: "INVENTOR",   hint: "Creates new things",                  category: "People" },
  { id: 299, level: "children_hard", word: "LIBRARIAN",  hint: "Looks after books in a library",      category: "People" },
  { id: 300, level: "children_hard", word: "MAGICIAN",   hint: "Performs magic tricks",                category: "People" },
  // Places
  { id: 301, level: "children_hard", word: "HOSPITAL",   hint: "Where you go if you are very sick",   category: "Places" },
  { id: 302, level: "children_hard", word: "TREASURE",   hint: "Hidden gold and jewels",              category: "Places" },
  { id: 303, level: "children_hard", word: "CLASSROOM",  hint: "The room where you learn at school",  category: "Places" },
  { id: 304, level: "children_hard", word: "AQUARIUM",   hint: "A place to see fish and sea life",    category: "Places" },
  { id: 305, level: "children_hard", word: "MUSEUM",     hint: "A building full of interesting old things", category: "Places" },
  { id: 306, level: "children_hard", word: "PYRAMID",    hint: "A triangle-shaped building in Egypt", category: "Places" },
  { id: 307, level: "children_hard", word: "LIGHTHOUSE",  hint: "A tower with a light to guide ships", category: "Places" },
  // Ideas & Describing
  { id: 308, level: "children_hard", word: "KNOWLEDGE",  hint: "What you gain from learning",         category: "Ideas" },
  { id: 309, level: "children_hard", word: "STRENGTH",   hint: "Being very powerful",                 category: "Ideas" },
  { id: 310, level: "children_hard", word: "ADVENTURE",  hint: "An exciting journey or experience",   category: "Ideas" },
  { id: 311, level: "children_hard", word: "INVISIBLE",  hint: "Cannot be seen",                      category: "Ideas" },
  { id: 312, level: "children_hard", word: "DANGEROUS",  hint: "Could hurt you",                      category: "Ideas" },
  { id: 313, level: "children_hard", word: "BEAUTIFUL",  hint: "Very pretty to look at",              category: "Ideas" },
  { id: 314, level: "children_hard", word: "WONDERFUL",  hint: "Really really good",                  category: "Ideas" },
  { id: 315, level: "children_hard", word: "ENORMOUS",   hint: "Extremely big",                       category: "Ideas" },
  { id: 316, level: "children_hard", word: "BRILLIANT",  hint: "Very clever or very bright",          category: "Ideas" },
  // Transport
  { id: 317, level: "children_hard", word: "HELICOPTER", hint: "Flying machine with spinning blades", category: "Transport" },
  { id: 318, level: "children_hard", word: "SUBMARINE",  hint: "A boat that goes underwater",         category: "Transport" },
  { id: 319, level: "children_hard", word: "AMBULANCE",  hint: "Rushes sick people to hospital",      category: "Transport" },
  { id: 320, level: "children_hard", word: "SPACESHIP",  hint: "A vehicle that flies to space",       category: "Transport" },

  // ══════════════════════════════════════════════════════════════════
  // ── Adult Standard ──
  // ══════════════════════════════════════════════════════════════════
  // Vocabulary
  { id: 321, level: "adult_standard", word: "EPHEMERAL",     hint: "Lasting a very short time",             category: "Vocabulary" },
  { id: 322, level: "adult_standard", word: "QUIXOTIC",      hint: "Extremely idealistic and unrealistic",  category: "Vocabulary" },
  { id: 323, level: "adult_standard", word: "JUXTAPOSE",     hint: "Place side by side for contrast",       category: "Vocabulary" },
  { id: 324, level: "adult_standard", word: "SYCOPHANT",     hint: "A servile flatterer",                   category: "Vocabulary" },
  { id: 325, level: "adult_standard", word: "CLANDESTINE",   hint: "Done in secret",                        category: "Vocabulary" },
  { id: 326, level: "adult_standard", word: "UBIQUITOUS",    hint: "Found everywhere",                      category: "Vocabulary" },
  { id: 327, level: "adult_standard", word: "CONUNDRUM",     hint: "A confusing problem",                   category: "Vocabulary" },
  { id: 328, level: "adult_standard", word: "ANTITHESIS",    hint: "The direct opposite",                   category: "Vocabulary" },
  { id: 329, level: "adult_standard", word: "AMBIGUOUS",     hint: "Open to more than one meaning",         category: "Vocabulary" },
  { id: 330, level: "adult_standard", word: "BENEVOLENT",    hint: "Well-meaning and kindly",               category: "Vocabulary" },
  { id: 331, level: "adult_standard", word: "CACOPHONY",     hint: "A harsh mixture of sounds",             category: "Vocabulary" },
  { id: 332, level: "adult_standard", word: "DEBACLE",       hint: "A sudden disastrous failure",           category: "Vocabulary" },
  { id: 333, level: "adult_standard", word: "ELOQUENT",      hint: "Fluent and persuasive in speaking",     category: "Vocabulary" },
  { id: 334, level: "adult_standard", word: "FASTIDIOUS",    hint: "Very attentive to detail",              category: "Vocabulary" },
  { id: 335, level: "adult_standard", word: "GREGARIOUS",    hint: "Fond of company; sociable",             category: "Vocabulary" },
  { id: 336, level: "adult_standard", word: "HARBINGER",     hint: "A forerunner of something",             category: "Vocabulary" },
  { id: 337, level: "adult_standard", word: "IMPETUOUS",     hint: "Acting quickly without thought",        category: "Vocabulary" },
  { id: 338, level: "adult_standard", word: "JUXTAPOSE",     hint: "Place side by side for contrast",       category: "Vocabulary" },
  { id: 339, level: "adult_standard", word: "LETHARGIC",     hint: "Lacking energy; sluggish",              category: "Vocabulary" },
  { id: 340, level: "adult_standard", word: "METICULOUS",    hint: "Showing great attention to detail",     category: "Vocabulary" },
  { id: 341, level: "adult_standard", word: "NEFARIOUS",     hint: "Wicked or criminal",                    category: "Vocabulary" },
  { id: 342, level: "adult_standard", word: "OBSTINATE",     hint: "Stubbornly refusing to change",         category: "Vocabulary" },
  { id: 343, level: "adult_standard", word: "PENCHANT",      hint: "A strong liking for something",         category: "Vocabulary" },
  { id: 344, level: "adult_standard", word: "RESILIENT",     hint: "Able to recover quickly",               category: "Vocabulary" },
  { id: 345, level: "adult_standard", word: "SAGACIOUS",     hint: "Having keen mental discernment",        category: "Vocabulary" },
  { id: 346, level: "adult_standard", word: "TENACIOUS",     hint: "Holding firmly; persistent",            category: "Vocabulary" },
  { id: 347, level: "adult_standard", word: "VIVACIOUS",     hint: "Attractively lively",                   category: "Vocabulary" },
  { id: 348, level: "adult_standard", word: "WHIMSICAL",     hint: "Playfully quaint or fanciful",          category: "Vocabulary" },
  { id: 349, level: "adult_standard", word: "ZEALOUS",       hint: "Having great energy for a cause",       category: "Vocabulary" },
  { id: 350, level: "adult_standard", word: "ANOMALY",       hint: "Something that deviates from normal",   category: "Vocabulary" },
  { id: 351, level: "adult_standard", word: "BREVITY",       hint: "Concise and exact use of words",        category: "Vocabulary" },
  { id: 352, level: "adult_standard", word: "CANDOUR",       hint: "The quality of being open and honest",  category: "Vocabulary" },
  { id: 353, level: "adult_standard", word: "DILIGENT",      hint: "Careful and persistent in work",        category: "Vocabulary" },
  { id: 354, level: "adult_standard", word: "EXQUISITE",     hint: "Extremely beautiful and delicate",      category: "Vocabulary" },
  { id: 355, level: "adult_standard", word: "FERVENT",       hint: "Having intense feeling",                category: "Vocabulary" },
  { id: 356, level: "adult_standard", word: "GRATITUDE",     hint: "The quality of being thankful",         category: "Vocabulary" },
  { id: 357, level: "adult_standard", word: "HIERARCHY",     hint: "A system of ranking",                   category: "Vocabulary" },
  { id: 358, level: "adult_standard", word: "IMMINENT",      hint: "About to happen",                       category: "Vocabulary" },
  { id: 359, level: "adult_standard", word: "JUBILANT",      hint: "Feeling great happiness",               category: "Vocabulary" },
  { id: 360, level: "adult_standard", word: "LUCRATIVE",     hint: "Producing a great deal of profit",      category: "Vocabulary" },
  { id: 361, level: "adult_standard", word: "MUNDANE",       hint: "Lacking interest; dull",                category: "Vocabulary" },
  { id: 362, level: "adult_standard", word: "NUANCE",        hint: "A subtle difference in meaning",        category: "Vocabulary" },
  { id: 363, level: "adult_standard", word: "OPULENT",       hint: "Ostentatiously rich and luxurious",     category: "Vocabulary" },
  { id: 364, level: "adult_standard", word: "PRAGMATIC",     hint: "Dealing with things sensibly",          category: "Vocabulary" },
  { id: 365, level: "adult_standard", word: "QUERULOUS",     hint: "Complaining in a whiny manner",         category: "Vocabulary" },
  { id: 366, level: "adult_standard", word: "RHETORIC",      hint: "The art of persuasive speaking",        category: "Vocabulary" },
  { id: 367, level: "adult_standard", word: "STOIC",         hint: "Enduring pain without complaint",       category: "Vocabulary" },
  { id: 368, level: "adult_standard", word: "TANGIBLE",      hint: "Clear and definite; able to be touched", category: "Vocabulary" },
  { id: 369, level: "adult_standard", word: "UNKEMPT",       hint: "Having an untidy appearance",           category: "Vocabulary" },
  { id: 370, level: "adult_standard", word: "VERBOSE",       hint: "Using more words than needed",          category: "Vocabulary" },
  { id: 371, level: "adult_standard", word: "WISTFUL",       hint: "Having a feeling of vague longing",     category: "Vocabulary" },
  { id: 372, level: "adult_standard", word: "ACCOLADE",      hint: "An award or privilege",                 category: "Vocabulary" },
  { id: 373, level: "adult_standard", word: "BRAVADO",       hint: "A bold manner to impress",              category: "Vocabulary" },
  { id: 374, level: "adult_standard", word: "CATALYST",      hint: "Something that causes change",          category: "Vocabulary" },
  { id: 375, level: "adult_standard", word: "DEXTERITY",     hint: "Skill in performing tasks",             category: "Vocabulary" },
  { id: 376, level: "adult_standard", word: "ENIGMA",        hint: "A puzzling or mysterious person",       category: "Vocabulary" },
  { id: 377, level: "adult_standard", word: "FIASCO",        hint: "A complete failure",                    category: "Vocabulary" },
  { id: 378, level: "adult_standard", word: "GRANDIOSE",     hint: "Impressive and imposing",               category: "Vocabulary" },
  { id: 379, level: "adult_standard", word: "HUBRIS",        hint: "Excessive pride or self-confidence",    category: "Vocabulary" },
  { id: 380, level: "adult_standard", word: "INNATE",        hint: "Inborn; natural",                       category: "Vocabulary" },
  { id: 381, level: "adult_standard", word: "JOVIAL",        hint: "Cheerful and friendly",                 category: "Vocabulary" },
  { id: 382, level: "adult_standard", word: "KINETIC",       hint: "Relating to or resulting from motion",  category: "Vocabulary" },
  { id: 383, level: "adult_standard", word: "LACONIC",       hint: "Using very few words",                  category: "Vocabulary" },
  { id: 384, level: "adult_standard", word: "MAVERICK",      hint: "An independent-minded person",          category: "Vocabulary" },
  { id: 385, level: "adult_standard", word: "NOMINAL",       hint: "In name only; very small",              category: "Vocabulary" },
  { id: 386, level: "adult_standard", word: "OMINOUS",       hint: "Giving the impression of bad things",   category: "Vocabulary" },
  { id: 387, level: "adult_standard", word: "PARADOX",       hint: "A seemingly contradictory statement",   category: "Vocabulary" },
  { id: 388, level: "adult_standard", word: "QUINTESSENTIAL", hint: "The most perfect example",             category: "Vocabulary" },
  // Feelings
  { id: 389, level: "adult_standard", word: "MELANCHOLY",    hint: "Deep sadness",                          category: "Feelings" },
  { id: 390, level: "adult_standard", word: "EUPHORIA",      hint: "Intense excitement and happiness",      category: "Feelings" },
  { id: 391, level: "adult_standard", word: "NOSTALGIA",     hint: "Sentimental longing for the past",      category: "Feelings" },
  { id: 392, level: "adult_standard", word: "ANGUISH",       hint: "Severe mental or physical suffering",   category: "Feelings" },
  { id: 393, level: "adult_standard", word: "CONTEMPT",      hint: "A feeling that something is worthless", category: "Feelings" },
  { id: 394, level: "adult_standard", word: "SERENITY",      hint: "The state of being calm and peaceful",  category: "Feelings" },
  { id: 395, level: "adult_standard", word: "EMPATHY",       hint: "Ability to understand others' feelings", category: "Feelings" },
  // Tech
  { id: 396, level: "adult_standard", word: "ALGORITHM",     hint: "Step-by-step problem solving",          category: "Tech" },
  { id: 397, level: "adult_standard", word: "BANDWIDTH",     hint: "Data transmission capacity",            category: "Tech" },
  { id: 398, level: "adult_standard", word: "COMPILER",      hint: "Translates code to machine language",   category: "Tech" },
  { id: 399, level: "adult_standard", word: "DATABASE",      hint: "Organised collection of information",   category: "Tech" },
  { id: 400, level: "adult_standard", word: "ENCRYPTION",    hint: "Converting data into secret code",      category: "Tech" },
  { id: 401, level: "adult_standard", word: "FIRMWARE",      hint: "Software embedded in hardware",         category: "Tech" },
  { id: 402, level: "adult_standard", word: "GIGABYTE",      hint: "A unit of digital storage",             category: "Tech" },
  { id: 403, level: "adult_standard", word: "HYPERLINK",     hint: "A clickable reference on a webpage",    category: "Tech" },
  { id: 404, level: "adult_standard", word: "INTERFACE",     hint: "A point where systems interact",        category: "Tech" },
  { id: 405, level: "adult_standard", word: "JAVASCRIPT",    hint: "A popular programming language",        category: "Tech" },
  { id: 406, level: "adult_standard", word: "KERNEL",        hint: "The core of an operating system",       category: "Tech" },
  { id: 407, level: "adult_standard", word: "LATENCY",       hint: "A delay in data transmission",          category: "Tech" },
  { id: 408, level: "adult_standard", word: "METADATA",      hint: "Data that describes other data",        category: "Tech" },
  { id: 409, level: "adult_standard", word: "PROTOCOL",      hint: "A set of rules for communication",      category: "Tech" },
  { id: 410, level: "adult_standard", word: "RECURSIVE",     hint: "A function that calls itself",          category: "Tech" },
  { id: 411, level: "adult_standard", word: "SYNTHESIS",     hint: "Combining parts into a whole",          category: "Tech" },
  { id: 412, level: "adult_standard", word: "TRANSISTOR",    hint: "A semiconductor device in circuits",    category: "Tech" },
  { id: 413, level: "adult_standard", word: "DEBUGGER",      hint: "Tool for finding code errors",          category: "Tech" },
  // Music
  { id: 414, level: "adult_standard", word: "RHYTHMIC",      hint: "Having a strong regular beat",          category: "Music" },
  { id: 415, level: "adult_standard", word: "SAXOPHONE",     hint: "Jazz instrument",                       category: "Music" },
  { id: 416, level: "adult_standard", word: "CRESCENDO",     hint: "A gradual increase in loudness",        category: "Music" },
  { id: 417, level: "adult_standard", word: "SYMPHONY",      hint: "A long composition for orchestra",      category: "Music" },
  { id: 418, level: "adult_standard", word: "BARITONE",      hint: "A male voice between tenor and bass",   category: "Music" },
  { id: 419, level: "adult_standard", word: "HARMONICA",     hint: "A small instrument you blow into",      category: "Music" },
  { id: 420, level: "adult_standard", word: "STACCATO",      hint: "Short detached musical notes",          category: "Music" },
  { id: 421, level: "adult_standard", word: "FORTISSIMO",    hint: "Very loud, in music",                   category: "Music" },
  { id: 422, level: "adult_standard", word: "SOPRANO",       hint: "The highest singing voice",             category: "Music" },
  // Art
  { id: 423, level: "adult_standard", word: "SILHOUETTE",    hint: "Dark outline against light",            category: "Art" },
  { id: 424, level: "adult_standard", word: "CHIAROSCURO",   hint: "Use of light and dark in painting",     category: "Art" },
  { id: 425, level: "adult_standard", word: "MOSAIC",        hint: "A picture made of small coloured pieces", category: "Art" },
  { id: 426, level: "adult_standard", word: "SCULPTURE",     hint: "A 3D work of art",                      category: "Art" },
  { id: 427, level: "adult_standard", word: "AESTHETIC",     hint: "Concerned with beauty",                 category: "Art" },
  { id: 428, level: "adult_standard", word: "FRESCO",        hint: "Painting on fresh wet plaster",         category: "Art" },
  // Nature
  { id: 429, level: "adult_standard", word: "CHRYSALIS",     hint: "Butterfly cocoon stage",                category: "Nature" },
  { id: 430, level: "adult_standard", word: "STALACTITE",    hint: "Icicle-shaped deposit hanging from a cave ceiling", category: "Nature" },
  { id: 431, level: "adult_standard", word: "ESTUARY",       hint: "Where a river meets the sea",           category: "Nature" },
  { id: 432, level: "adult_standard", word: "SOLSTICE",      hint: "Longest or shortest day of the year",   category: "Nature" },
  { id: 433, level: "adult_standard", word: "TUNDRA",        hint: "Vast flat treeless Arctic region",      category: "Nature" },
  { id: 434, level: "adult_standard", word: "SAVANNAH",      hint: "A grassy plain with few trees",         category: "Nature" },
  { id: 435, level: "adult_standard", word: "TEMPEST",       hint: "A violent windy storm",                 category: "Nature" },
  { id: 436, level: "adult_standard", word: "AURORA",        hint: "Natural light display near the poles",  category: "Nature" },
  // Medical
  { id: 437, level: "adult_standard", word: "PNEUMONIA",     hint: "Lung infection",                        category: "Medical" },
  { id: 438, level: "adult_standard", word: "DIAGNOSIS",     hint: "Identification of an illness",          category: "Medical" },
  { id: 439, level: "adult_standard", word: "PROGNOSIS",     hint: "Predicted course of a disease",         category: "Medical" },
  { id: 440, level: "adult_standard", word: "SYMPTOM",       hint: "A sign of an illness",                  category: "Medical" },
  { id: 441, level: "adult_standard", word: "ANTIBIOTIC",    hint: "Medicine that fights bacteria",         category: "Medical" },
  { id: 442, level: "adult_standard", word: "STETHOSCOPE",   hint: "Instrument for listening to heartbeats", category: "Medical" },
  // Geography
  { id: 443, level: "adult_standard", word: "ARCHIPELAGO",   hint: "Chain of islands",                      category: "Geography" },
  { id: 444, level: "adult_standard", word: "PENINSULA",     hint: "Land nearly surrounded by water",       category: "Geography" },
  { id: 445, level: "adult_standard", word: "PLATEAU",       hint: "A high flat area of land",              category: "Geography" },
  { id: 446, level: "adult_standard", word: "FJORD",         hint: "A long narrow inlet between cliffs",    category: "Geography" },
  { id: 447, level: "adult_standard", word: "MERIDIAN",      hint: "An imaginary line from pole to pole",   category: "Geography" },
  { id: 448, level: "adult_standard", word: "CARTOGRAPHY",   hint: "The art of making maps",                category: "Geography" },
  { id: 449, level: "adult_standard", word: "LATITUDE",      hint: "Distance north or south of the equator", category: "Geography" },
  // Language
  { id: 450, level: "adult_standard", word: "PALINDROME",    hint: "Reads same forwards and back",          category: "Language" },
  { id: 451, level: "adult_standard", word: "METAPHOR",      hint: "A figure of speech comparing two things", category: "Language" },
  { id: 452, level: "adult_standard", word: "HYPERBOLE",     hint: "Exaggerated statements not meant literally", category: "Language" },
  { id: 453, level: "adult_standard", word: "OXYMORON",      hint: "Contradictory terms together",          category: "Language" },
  { id: 454, level: "adult_standard", word: "EUPHEMISM",     hint: "A mild expression for something harsh", category: "Language" },
  { id: 455, level: "adult_standard", word: "ALLEGORY",      hint: "A story with a hidden meaning",         category: "Language" },
  { id: 456, level: "adult_standard", word: "SYNTAX",        hint: "The arrangement of words in sentences", category: "Language" },
  { id: 457, level: "adult_standard", word: "ETYMOLOGY",     hint: "The origin and history of words",       category: "Language" },
  // Culture
  { id: 458, level: "adult_standard", word: "ZEITGEIST",     hint: "Spirit of the times",                   category: "Culture" },
  { id: 459, level: "adult_standard", word: "RENAISSANCE",   hint: "A revival of art and learning",         category: "Culture" },
  { id: 460, level: "adult_standard", word: "BOHEMIAN",      hint: "An unconventional artistic lifestyle",  category: "Culture" },
  { id: 461, level: "adult_standard", word: "ETIQUETTE",     hint: "Rules of polite behaviour",             category: "Culture" },
  // Things
  { id: 462, level: "adult_standard", word: "KALEIDOSCOPE",  hint: "Tube showing colourful patterns",       category: "Things" },
  { id: 463, level: "adult_standard", word: "CHANDELIER",    hint: "An ornate hanging light fixture",       category: "Things" },
  { id: 464, level: "adult_standard", word: "GUILLOTINE",    hint: "A device for cutting paper or worse",   category: "Things" },
  // Places
  { id: 465, level: "adult_standard", word: "LABYRINTH",     hint: "A complex maze",                        category: "Places" },
  { id: 466, level: "adult_standard", word: "CATACOMB",      hint: "An underground cemetery",               category: "Places" },
  { id: 467, level: "adult_standard", word: "COLOSSEUM",     hint: "Ancient Roman amphitheatre",            category: "Places" },
  // Science
  { id: 468, level: "adult_standard", word: "MOLECULE",      hint: "A group of atoms bonded together",      category: "Science" },
  { id: 469, level: "adult_standard", word: "HYPOTHESIS",    hint: "A proposed explanation for something",  category: "Science" },
  { id: 470, level: "adult_standard", word: "PHOTOSYNTHESIS", hint: "How plants make food from sunlight",   category: "Science" },
  { id: 471, level: "adult_standard", word: "EVOLUTION",     hint: "Gradual change in species over time",   category: "Science" },
  { id: 472, level: "adult_standard", word: "CENTRIFUGAL",   hint: "Moving away from the centre",           category: "Science" },
  { id: 473, level: "adult_standard", word: "QUANTUM",       hint: "The smallest possible discrete unit",   category: "Science" },
  { id: 474, level: "adult_standard", word: "OSMOSIS",       hint: "Movement of water through a membrane",  category: "Science" },
  { id: 475, level: "adult_standard", word: "CATALYST",      hint: "A substance that speeds up a reaction", category: "Science" },
  // History
  { id: 476, level: "adult_standard", word: "MEDIEVAL",      hint: "Relating to the Middle Ages",           category: "History" },
  { id: 477, level: "adult_standard", word: "GLADIATOR",     hint: "An ancient Roman fighter",              category: "History" },
  { id: 478, level: "adult_standard", word: "PHARAOH",       hint: "An ancient Egyptian ruler",             category: "History" },
  { id: 479, level: "adult_standard", word: "DYNASTY",       hint: "A line of rulers from the same family", category: "History" },
  { id: 480, level: "adult_standard", word: "ARMISTICE",     hint: "An agreement to stop fighting",         category: "History" },
  // Philosophy
  { id: 481, level: "adult_standard", word: "EXISTENTIAL",   hint: "Relating to human existence",           category: "Philosophy" },
  { id: 482, level: "adult_standard", word: "NIHILISM",      hint: "Rejection of all moral principles",     category: "Philosophy" },
  { id: 483, level: "adult_standard", word: "ALTRUISM",      hint: "Selfless concern for others",           category: "Philosophy" },
  { id: 484, level: "adult_standard", word: "EMPIRICAL",     hint: "Based on observation rather than theory", category: "Philosophy" },
  { id: 485, level: "adult_standard", word: "DICHOTOMY",     hint: "A division into two opposing groups",   category: "Philosophy" },

  // ══════════════════════════════════════════════════════════════════
  // ── Adult Challenge ──
  // ══════════════════════════════════════════════════════════════════
  // Language
  { id: 486, level: "adult_challenge", word: "ONOMATOPOEIA",    hint: "Words that sound like their meaning",       category: "Language" },
  { id: 487, level: "adult_challenge", word: "SESQUIPEDALIAN",  hint: "Relating to long words",                    category: "Language" },
  { id: 488, level: "adult_challenge", word: "PORTMANTEAU",     hint: "A word blending two others",                category: "Language" },
  { id: 489, level: "adult_challenge", word: "SYNECDOCHE",      hint: "A part representing the whole",             category: "Language" },
  { id: 490, level: "adult_challenge", word: "MALAPROPISM",     hint: "Mistaken use of a similar-sounding word",   category: "Language" },
  { id: 491, level: "adult_challenge", word: "DIPHTHONG",       hint: "A gliding vowel sound",                     category: "Language" },
  { id: 492, level: "adult_challenge", word: "SOLILOQUY",       hint: "Speaking one's thoughts aloud alone",        category: "Language" },
  { id: 493, level: "adult_challenge", word: "ANACHRONISM",     hint: "Something out of its time period",          category: "Language" },
  // Vocabulary
  { id: 494, level: "adult_challenge", word: "SERENDIPITY",     hint: "Happy accident",                            category: "Vocabulary" },
  { id: 495, level: "adult_challenge", word: "ACQUIESCE",       hint: "Accept reluctantly without protest",        category: "Vocabulary" },
  { id: 496, level: "adult_challenge", word: "IDIOSYNCRASY",    hint: "A peculiar personal habit",                 category: "Vocabulary" },
  { id: 497, level: "adult_challenge", word: "CONSCIENTIOUS",   hint: "Thorough and careful",                      category: "Vocabulary" },
  { id: 498, level: "adult_challenge", word: "KNOWLEDGEABLE",   hint: "Well-informed",                             category: "Vocabulary" },
  { id: 499, level: "adult_challenge", word: "ACQUAINTANCE",    hint: "A person known slightly",                   category: "Vocabulary" },
  { id: 500, level: "adult_challenge", word: "BOURGEOISIE",     hint: "The middle class in Marxist theory",        category: "Vocabulary" },
  { id: 501, level: "adult_challenge", word: "LOQUACIOUS",      hint: "Tending to talk a great deal",              category: "Vocabulary" },
  { id: 502, level: "adult_challenge", word: "MAGNANIMOUS",     hint: "Generous or forgiving",                     category: "Vocabulary" },
  { id: 503, level: "adult_challenge", word: "OBSEQUIOUS",      hint: "Excessively obedient or attentive",         category: "Vocabulary" },
  { id: 504, level: "adult_challenge", word: "PERSPICACIOUS",   hint: "Having keen mental perception",             category: "Vocabulary" },
  { id: 505, level: "adult_challenge", word: "RECALCITRANT",    hint: "Stubbornly uncooperative",                  category: "Vocabulary" },
  { id: 506, level: "adult_challenge", word: "SUPERCILIOUS",    hint: "Behaving as if superior to others",         category: "Vocabulary" },
  { id: 507, level: "adult_challenge", word: "SURREPTITIOUS",   hint: "Kept secret because improper",              category: "Vocabulary" },
  { id: 508, level: "adult_challenge", word: "TERGIVERSATION",  hint: "Evasion of straightforward statement",      category: "Vocabulary" },
  { id: 509, level: "adult_challenge", word: "VERISIMILITUDE",  hint: "The appearance of being true",              category: "Vocabulary" },
  { id: 510, level: "adult_challenge", word: "PUSILLANIMOUS",   hint: "Showing a lack of courage",                 category: "Vocabulary" },
  { id: 511, level: "adult_challenge", word: "PULCHRITUDINOUS", hint: "Physically beautiful",                      category: "Vocabulary" },
  { id: 512, level: "adult_challenge", word: "SESQUICENTENNIAL", hint: "A 150th anniversary",                      category: "Vocabulary" },
  { id: 513, level: "adult_challenge", word: "ANTEDILUVIAN",    hint: "Extremely old-fashioned",                   category: "Vocabulary" },
  { id: 514, level: "adult_challenge", word: "CONFLAGRATION",   hint: "An extensive fire",                         category: "Vocabulary" },
  { id: 515, level: "adult_challenge", word: "DEFENESTRATION",  hint: "Throwing someone out of a window",          category: "Vocabulary" },
  { id: 516, level: "adult_challenge", word: "GRANDILOQUENT",   hint: "Pompous or extravagant in language",        category: "Vocabulary" },
  { id: 517, level: "adult_challenge", word: "INEFFABLE",       hint: "Too great to be expressed in words",        category: "Vocabulary" },
  { id: 518, level: "adult_challenge", word: "JUXTAPOSITION",   hint: "The fact of placing things side by side",   category: "Vocabulary" },
  { id: 519, level: "adult_challenge", word: "LEGERDEMAIN",     hint: "Skilful use of one's hands; trickery",      category: "Vocabulary" },
  { id: 520, level: "adult_challenge", word: "PHANTASMAGORIA",  hint: "A sequence of dreamlike imagery",           category: "Vocabulary" },
  { id: 521, level: "adult_challenge", word: "PRESTIDIGITATION", hint: "Magic tricks performed as entertainment",  category: "Vocabulary" },
  { id: 522, level: "adult_challenge", word: "SESQUIPEDALIAN",  hint: "Given to using long words",                 category: "Vocabulary" },
  { id: 523, level: "adult_challenge", word: "SYCOPHANTIC",     hint: "Behaving in an excessively flattering way", category: "Vocabulary" },
  { id: 524, level: "adult_challenge", word: "TINTINNABULATION", hint: "A ringing or tinkling sound",              category: "Vocabulary" },
  { id: 525, level: "adult_challenge", word: "DISENFRANCHISE",  hint: "Deprive of a right or privilege",           category: "Vocabulary" },
  // Society
  { id: 526, level: "adult_challenge", word: "BUREAUCRACY",     hint: "Excessive administrative procedures",       category: "Society" },
  { id: 527, level: "adult_challenge", word: "SURVEILLANCE",    hint: "Close observation",                         category: "Society" },
  { id: 528, level: "adult_challenge", word: "TOTALITARIAN",    hint: "Exercising absolute state control",         category: "Society" },
  { id: 529, level: "adult_challenge", word: "PROPAGANDA",      hint: "Misleading information to promote a cause", category: "Society" },
  { id: 530, level: "adult_challenge", word: "OLIGARCHY",       hint: "Government by a small group",               category: "Society" },
  { id: 531, level: "adult_challenge", word: "PLUTOCRACY",      hint: "Government by the wealthy",                 category: "Society" },
  { id: 532, level: "adult_challenge", word: "GERRYMANDERING",  hint: "Manipulating electoral boundaries",         category: "Society" },
  { id: 533, level: "adult_challenge", word: "FILIBUSTER",      hint: "An obstructive speech in parliament",       category: "Society" },
  // Medical
  { id: 534, level: "adult_challenge", word: "HEMORRHAGE",      hint: "Severe bleeding",                           category: "Medical" },
  { id: 535, level: "adult_challenge", word: "OPHTHALMOLOGY",   hint: "The study of eye diseases",                 category: "Medical" },
  { id: 536, level: "adult_challenge", word: "ANEURYSM",        hint: "A bulge in a blood vessel wall",            category: "Medical" },
  { id: 537, level: "adult_challenge", word: "TRACHEOTOMY",     hint: "A surgical opening in the windpipe",        category: "Medical" },
  { id: 538, level: "adult_challenge", word: "SCHIZOPHRENIA",   hint: "A serious mental disorder",                 category: "Medical" },
  { id: 539, level: "adult_challenge", word: "ANAESTHESIA",     hint: "Loss of sensation, especially for surgery", category: "Medical" },
  { id: 540, level: "adult_challenge", word: "HYPOCHONDRIAC",   hint: "A person who worries excessively about health", category: "Medical" },
  { id: 541, level: "adult_challenge", word: "PHARMACEUTICAL",  hint: "Relating to medicinal drugs",               category: "Medical" },
  // Science
  { id: 542, level: "adult_challenge", word: "PTERODACTYL",     hint: "Flying prehistoric reptile",                category: "Science" },
  { id: 543, level: "adult_challenge", word: "ELECTROMAGNETIC",  hint: "Relating to electric and magnetic fields",   category: "Science" },
  { id: 544, level: "adult_challenge", word: "DEOXYRIBONUCLEIC", hint: "The D in DNA",                             category: "Science" },
  { id: 545, level: "adult_challenge", word: "CHRYSANTHEMUM",   hint: "A flowering plant with dense blooms",       category: "Science" },
  { id: 546, level: "adult_challenge", word: "BIOLUMINESCENCE", hint: "Light produced by living organisms",        category: "Science" },
  { id: 547, level: "adult_challenge", word: "ARCHAEOPTERYX",   hint: "An early bird-like dinosaur",               category: "Science" },
  { id: 548, level: "adult_challenge", word: "NEUROPLASTICITY", hint: "The brain's ability to reorganise itself",  category: "Science" },
  { id: 549, level: "adult_challenge", word: "ELECTROLYSIS",    hint: "Chemical decomposition by electric current", category: "Science" },
  { id: 550, level: "adult_challenge", word: "MITOCHONDRIA",    hint: "The powerhouse of the cell",                category: "Science" },
  { id: 551, level: "adult_challenge", word: "PALAEONTOLOGY",   hint: "The study of ancient life through fossils", category: "Science" },
  // Music
  { id: 552, level: "adult_challenge", word: "XYLOPHONE",       hint: "Musical instrument with wooden bars",       category: "Music" },
  { id: 553, level: "adult_challenge", word: "HARPSICHORD",     hint: "A keyboard instrument like a piano",        category: "Music" },
  { id: 554, level: "adult_challenge", word: "GLOCKENSPIEL",    hint: "A percussion instrument with metal plates", category: "Music" },
  { id: 555, level: "adult_challenge", word: "DIDGERIDOO",      hint: "An Australian wind instrument",             category: "Music" },
  { id: 556, level: "adult_challenge", word: "CONTRABASSOON",   hint: "The lowest-pitched woodwind instrument",    category: "Music" },
  // Military
  { id: 557, level: "adult_challenge", word: "RECONNAISSANCE",  hint: "Military observation mission",              category: "Military" },
  { id: 558, level: "adult_challenge", word: "GUERRILLA",       hint: "Irregular warfare by small groups",         category: "Military" },
  { id: 559, level: "adult_challenge", word: "CAMOUFLAGE",      hint: "Disguise to blend in with surroundings",    category: "Military" },
  { id: 560, level: "adult_challenge", word: "MANOEUVRE",        hint: "A carefully planned military movement",     category: "Military" },
  // Learning
  { id: 561, level: "adult_challenge", word: "MNEMONIC",        hint: "Memory aid technique",                      category: "Learning" },
  { id: 562, level: "adult_challenge", word: "PEDAGOGY",        hint: "The method and practice of teaching",       category: "Learning" },
  { id: 563, level: "adult_challenge", word: "CURRICULUM",      hint: "Subjects in a course of study",             category: "Learning" },
  { id: 564, level: "adult_challenge", word: "EPISTEMOLOGY",    hint: "The theory of knowledge",                   category: "Learning" },
  // Art
  { id: 565, level: "adult_challenge", word: "PSYCHEDELIC",     hint: "Mind-altering visual patterns",             category: "Art" },
  { id: 566, level: "adult_challenge", word: "TROMPE",          hint: "Visual illusion in art",                    category: "Art" },
  { id: 567, level: "adult_challenge", word: "DAGUERREOTYPE",   hint: "An early type of photograph",               category: "Art" },
  { id: 568, level: "adult_challenge", word: "CHIAROSCURO",     hint: "Contrasting light and dark in art",         category: "Art" },
  // Spelling traps
  { id: 569, level: "adult_challenge", word: "QUEUE",           hint: "A line of waiting people",                  category: "Vocabulary" },
  { id: 570, level: "adult_challenge", word: "RHYTHM",          hint: "A strong repeated pattern of sound",        category: "Vocabulary" },
  { id: 571, level: "adult_challenge", word: "PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS", hint: "A lung disease caused by volcanic dust", category: "Vocabulary" },
  { id: 572, level: "adult_challenge", word: "WORCESTERSHIRE",  hint: "A savoury English sauce",                   category: "Vocabulary" },
  { id: 573, level: "adult_challenge", word: "ONYCHOPHAGIST",   hint: "A person who bites their nails",            category: "Vocabulary" },
  { id: 574, level: "adult_challenge", word: "QUIZZACIOUSLY",   hint: "In a mocking manner",                       category: "Vocabulary" },
  { id: 575, level: "adult_challenge", word: "FLOCCINAUCINIHILIPILIFICATION", hint: "The estimation of something as worthless", category: "Vocabulary" },
  // Foreign-origin / tricky
  { id: 576, level: "adult_challenge", word: "ENTREPRENEUR",    hint: "A person who starts a business",            category: "Society" },
  { id: 577, level: "adult_challenge", word: "QUESTIONNAIRE",   hint: "A set of written questions for a survey",   category: "Society" },
  { id: 578, level: "adult_challenge", word: "CHAUFFEUR",       hint: "A person employed to drive a car",          category: "Society" },
  { id: 579, level: "adult_challenge", word: "CONNOISSEUR",     hint: "An expert judge in matters of taste",       category: "Society" },
  { id: 580, level: "adult_challenge", word: "RENDEZVOUS",      hint: "A meeting at an agreed time and place",     category: "Vocabulary" },
  { id: 581, level: "adult_challenge", word: "LIEUTENANT",      hint: "A deputy or second-in-command",             category: "Military" },
  { id: 582, level: "adult_challenge", word: "SILHOUETTE",      hint: "A dark outline against a lighter background", category: "Art" },
  { id: 583, level: "adult_challenge", word: "THOROUGHFARE",    hint: "A main road or public highway",             category: "Vocabulary" },
  { id: 584, level: "adult_challenge", word: "ONOMATOPOEIA",    hint: "Words imitating natural sounds",            category: "Language" },
  { id: 585, level: "adult_challenge", word: "CONSCIENTIOUS",   hint: "Wishing to do what is right",               category: "Vocabulary" },
  { id: 586, level: "adult_challenge", word: "MISCELLANEOUS",   hint: "Of various types; mixed",                   category: "Vocabulary" },
  { id: 587, level: "adult_challenge", word: "IDIOSYNCRATIC",   hint: "Peculiar to an individual",                 category: "Vocabulary" },
  { id: 588, level: "adult_challenge", word: "ECUMENICAL",      hint: "Representing the whole Christian world",    category: "Vocabulary" },
  { id: 589, level: "adult_challenge", word: "DISCOMBOBULATE",  hint: "To confuse or disconcert",                  category: "Vocabulary" },
  { id: 590, level: "adult_challenge", word: "FLIBBERTIGIBBET", hint: "A frivolous or gossipy person",             category: "Vocabulary" },
];

export default WORDS;

/**
 * Get a random word for the given game level.
 * @param {"children_easy"|"children_medium"|"children_hard"|"adult_standard"|"adult_challenge"} level
 * @returns {object} A word entry { id, level, word, hint, category }
 */
export function getRandomWord(level) {
  const pool = WORDS.filter(w => w.level === level);
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Map game mode + difficulty to a level key.
 * @param {"children"|"adult"} mode
 * @param {"easy"|"medium"|"hard"|"standard"|"challenge"} difficulty
 * @returns {string} The level key
 */
export function getLevel(mode, difficulty) {
  if (mode === "children") {
    if (difficulty === "easy") return "children_easy";
    if (difficulty === "medium") return "children_medium";
    return "children_hard";
  }
  return difficulty === "challenge" ? "adult_challenge" : "adult_standard";
}
